import './globals.css';

import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

const RootLayout = ({ children }: { children: React.ReactNode }) => (
    <html lang='pt-br'>
        <body className={inter.className}>{children}</body>
    </html>
);

export default RootLayout;
